# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'morph' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    # Required by Google Map, ignore if you use Apple Map
    pod 'GoogleMaps'
  # pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
