# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'morph' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
    # Required by Google Map, ignore if you use Apple Map
    pod 'GoogleMaps'
    pod 'react-native-maps', path: '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps' 

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end

      if target.name == "React"
          target.remove_from_project
      end
  end
end